name: Docker
on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ github.repository }}
          tags: |
            type=edge
            type=semver,pattern={{version}}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
